// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: api/tvx.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentType int32

const (
	PaymentType_Unknown      PaymentType = 0
	PaymentType_SoftCurrency PaymentType = 1
	PaymentType_HardCurrency PaymentType = 2
	PaymentType_Real         PaymentType = 3
	PaymentType_Crypto       PaymentType = 4
	PaymentType_ADS          PaymentType = 5
	PaymentType_Fre          PaymentType = 6
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "Unknown",
		1: "SoftCurrency",
		2: "HardCurrency",
		3: "Real",
		4: "Crypto",
		5: "ADS",
		6: "Fre",
	}
	PaymentType_value = map[string]int32{
		"Unknown":      0,
		"SoftCurrency": 1,
		"HardCurrency": 2,
		"Real":         3,
		"Crypto":       4,
		"ADS":          5,
		"Fre":          6,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tvx_proto_enumTypes[0].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_api_tvx_proto_enumTypes[0]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SetStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetStringRequest) Reset() {
	*x = SetStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStringRequest) ProtoMessage() {}

func (x *SetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStringRequest.ProtoReflect.Descriptor instead.
func (*SetStringRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{2}
}

func (x *SetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetStringResponse) Reset() {
	*x = SetStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStringResponse) ProtoMessage() {}

func (x *SetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStringResponse.ProtoReflect.Descriptor instead.
func (*SetStringResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{3}
}

type GetStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetStringRequest) Reset() {
	*x = GetStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStringRequest) ProtoMessage() {}

func (x *GetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStringRequest.ProtoReflect.Descriptor instead.
func (*GetStringRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{4}
}

func (x *GetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetStringResponse) Reset() {
	*x = GetStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStringResponse) ProtoMessage() {}

func (x *GetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStringResponse.ProtoReflect.Descriptor instead.
func (*GetStringResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{5}
}

func (x *GetStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetIntRequest) Reset() {
	*x = SetIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIntRequest) ProtoMessage() {}

func (x *SetIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIntRequest.ProtoReflect.Descriptor instead.
func (*SetIntRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{6}
}

func (x *SetIntRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetIntRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetIntResponse) Reset() {
	*x = SetIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIntResponse) ProtoMessage() {}

func (x *SetIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIntResponse.ProtoReflect.Descriptor instead.
func (*SetIntResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{7}
}

type GetIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetIntRequest) Reset() {
	*x = GetIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntRequest) ProtoMessage() {}

func (x *GetIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntRequest.ProtoReflect.Descriptor instead.
func (*GetIntRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{8}
}

func (x *GetIntRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetIntResponse) Reset() {
	*x = GetIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntResponse) ProtoMessage() {}

func (x *GetIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntResponse.ProtoReflect.Descriptor instead.
func (*GetIntResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{9}
}

func (x *GetIntResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetFloatRequest) Reset() {
	*x = SetFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFloatRequest) ProtoMessage() {}

func (x *SetFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFloatRequest.ProtoReflect.Descriptor instead.
func (*SetFloatRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{10}
}

func (x *SetFloatRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetFloatRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFloatResponse) Reset() {
	*x = SetFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFloatResponse) ProtoMessage() {}

func (x *SetFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFloatResponse.ProtoReflect.Descriptor instead.
func (*SetFloatResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{11}
}

type GetFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFloatRequest) Reset() {
	*x = GetFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloatRequest) ProtoMessage() {}

func (x *GetFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloatRequest.ProtoReflect.Descriptor instead.
func (*GetFloatRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{12}
}

func (x *GetFloatRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetFloatResponse) Reset() {
	*x = GetFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloatResponse) ProtoMessage() {}

func (x *GetFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloatResponse.ProtoReflect.Descriptor instead.
func (*GetFloatResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{13}
}

func (x *GetFloatResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType  PaymentType `protobuf:"varint,2,opt,name=payment_type,json=paymentType,proto3,enum=tvx.PaymentType" json:"payment_type,omitempty"`
	Price        float64     `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	IsConsumable bool        `protobuf:"varint,4,opt,name=is_consumable,json=isConsumable,proto3" json:"is_consumable,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{14}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetPaymentType() PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentType_Unknown
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetIsConsumable() bool {
	if x != nil {
		return x.IsConsumable
	}
	return false
}

type GetAvailableProductListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAvailableProductListRequest) Reset() {
	*x = GetAvailableProductListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableProductListRequest) ProtoMessage() {}

func (x *GetAvailableProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableProductListRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableProductListRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{15}
}

type GetAvailableProductListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *GetAvailableProductListResponse) Reset() {
	*x = GetAvailableProductListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableProductListResponse) ProtoMessage() {}

func (x *GetAvailableProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableProductListResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableProductListResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{16}
}

func (x *GetAvailableProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ConsumeProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConsumeProductRequest) Reset() {
	*x = ConsumeProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeProductRequest) ProtoMessage() {}

func (x *ConsumeProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeProductRequest.ProtoReflect.Descriptor instead.
func (*ConsumeProductRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{17}
}

func (x *ConsumeProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConsumeProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConsumeProductResponse) Reset() {
	*x = ConsumeProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeProductResponse) ProtoMessage() {}

func (x *ConsumeProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeProductResponse.ProtoReflect.Descriptor instead.
func (*ConsumeProductResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{18}
}

type GetConsumedProductListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConsumedProductListRequest) Reset() {
	*x = GetConsumedProductListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumedProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumedProductListRequest) ProtoMessage() {}

func (x *GetConsumedProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumedProductListRequest.ProtoReflect.Descriptor instead.
func (*GetConsumedProductListRequest) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{19}
}

type GetConsumedProductListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *GetConsumedProductListResponse) Reset() {
	*x = GetConsumedProductListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tvx_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumedProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumedProductListResponse) ProtoMessage() {}

func (x *GetConsumedProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tvx_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumedProductListResponse.ProtoReflect.Descriptor instead.
func (*GetConsumedProductListResponse) Descriptor() ([]byte, []int) {
	return file_api_tvx_proto_rawDescGZIP(), []int{20}
}

func (x *GetConsumedProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_api_tvx_proto protoreflect.FileDescriptor

var file_api_tvx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x76, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x74, 0x76, 0x78, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x3a, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x33, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x22, 0x27, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x2a, 0x66, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x6f, 0x66, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x48, 0x61, 0x72, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x6c, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x53, 0x10, 0x05, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x72, 0x65, 0x10, 0x06, 0x32, 0x86, 0x07, 0x0a, 0x0e, 0x43, 0x6c, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x41, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x11, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0b, 0x22, 0x06, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x4e,
	0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x76,
	0x78, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0c, 0x22, 0x07, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x3a, 0x01, 0x2a, 0x12, 0x51,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x76,
	0x78, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x7b, 0x6b, 0x65, 0x79,
	0x7d, 0x12, 0x42, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x76,
	0x78, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f, 0x69,
	0x6e, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x45, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x12,
	0x12, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c,
	0x12, 0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x2f, 0x7b, 0x6b, 0x65, 0x79, 0x7d, 0x12, 0x4a, 0x0a, 0x08,
	0x53, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x53,
	0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x74, 0x76, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x06, 0x2f,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x4d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x76, 0x78,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x0c, 0x2f, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x2f, 0x7b, 0x6b, 0x65, 0x79, 0x7d, 0x12, 0x80, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x74,
	0x76, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x3a, 0x01, 0x2a, 0x12, 0x7c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e,
	0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x74, 0x76, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x42, 0x14, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x0b, 0x74, 0x76, 0x78, 0x2e,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_tvx_proto_rawDescOnce sync.Once
	file_api_tvx_proto_rawDescData = file_api_tvx_proto_rawDesc
)

func file_api_tvx_proto_rawDescGZIP() []byte {
	file_api_tvx_proto_rawDescOnce.Do(func() {
		file_api_tvx_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_tvx_proto_rawDescData)
	})
	return file_api_tvx_proto_rawDescData
}

var file_api_tvx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_tvx_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_tvx_proto_goTypes = []interface{}{
	(PaymentType)(0),                        // 0: tvx.PaymentType
	(*LoginRequest)(nil),                    // 1: tvx.LoginRequest
	(*LoginResponse)(nil),                   // 2: tvx.LoginResponse
	(*SetStringRequest)(nil),                // 3: tvx.SetStringRequest
	(*SetStringResponse)(nil),               // 4: tvx.SetStringResponse
	(*GetStringRequest)(nil),                // 5: tvx.GetStringRequest
	(*GetStringResponse)(nil),               // 6: tvx.GetStringResponse
	(*SetIntRequest)(nil),                   // 7: tvx.SetIntRequest
	(*SetIntResponse)(nil),                  // 8: tvx.SetIntResponse
	(*GetIntRequest)(nil),                   // 9: tvx.GetIntRequest
	(*GetIntResponse)(nil),                  // 10: tvx.GetIntResponse
	(*SetFloatRequest)(nil),                 // 11: tvx.SetFloatRequest
	(*SetFloatResponse)(nil),                // 12: tvx.SetFloatResponse
	(*GetFloatRequest)(nil),                 // 13: tvx.GetFloatRequest
	(*GetFloatResponse)(nil),                // 14: tvx.GetFloatResponse
	(*Product)(nil),                         // 15: tvx.Product
	(*GetAvailableProductListRequest)(nil),  // 16: tvx.GetAvailableProductListRequest
	(*GetAvailableProductListResponse)(nil), // 17: tvx.GetAvailableProductListResponse
	(*ConsumeProductRequest)(nil),           // 18: tvx.ConsumeProductRequest
	(*ConsumeProductResponse)(nil),          // 19: tvx.ConsumeProductResponse
	(*GetConsumedProductListRequest)(nil),   // 20: tvx.GetConsumedProductListRequest
	(*GetConsumedProductListResponse)(nil),  // 21: tvx.GetConsumedProductListResponse
}
var file_api_tvx_proto_depIdxs = []int32{
	0,  // 0: tvx.Product.payment_type:type_name -> tvx.PaymentType
	15, // 1: tvx.GetAvailableProductListResponse.products:type_name -> tvx.Product
	15, // 2: tvx.GetConsumedProductListResponse.products:type_name -> tvx.Product
	1,  // 3: tvx.ClickerBackend.Login:input_type -> tvx.LoginRequest
	3,  // 4: tvx.ClickerBackend.SetString:input_type -> tvx.SetStringRequest
	5,  // 5: tvx.ClickerBackend.GetString:input_type -> tvx.GetStringRequest
	7,  // 6: tvx.ClickerBackend.SetInt:input_type -> tvx.SetIntRequest
	9,  // 7: tvx.ClickerBackend.GetInt:input_type -> tvx.GetIntRequest
	11, // 8: tvx.ClickerBackend.SetFloat:input_type -> tvx.SetFloatRequest
	13, // 9: tvx.ClickerBackend.GetFloat:input_type -> tvx.GetFloatRequest
	16, // 10: tvx.ClickerBackend.GetAvailableProductList:input_type -> tvx.GetAvailableProductListRequest
	18, // 11: tvx.ClickerBackend.ConsumeProduct:input_type -> tvx.ConsumeProductRequest
	20, // 12: tvx.ClickerBackend.GetConsumedProductList:input_type -> tvx.GetConsumedProductListRequest
	2,  // 13: tvx.ClickerBackend.Login:output_type -> tvx.LoginResponse
	4,  // 14: tvx.ClickerBackend.SetString:output_type -> tvx.SetStringResponse
	6,  // 15: tvx.ClickerBackend.GetString:output_type -> tvx.GetStringResponse
	8,  // 16: tvx.ClickerBackend.SetInt:output_type -> tvx.SetIntResponse
	10, // 17: tvx.ClickerBackend.GetInt:output_type -> tvx.GetIntResponse
	12, // 18: tvx.ClickerBackend.SetFloat:output_type -> tvx.SetFloatResponse
	14, // 19: tvx.ClickerBackend.GetFloat:output_type -> tvx.GetFloatResponse
	17, // 20: tvx.ClickerBackend.GetAvailableProductList:output_type -> tvx.GetAvailableProductListResponse
	19, // 21: tvx.ClickerBackend.ConsumeProduct:output_type -> tvx.ConsumeProductResponse
	21, // 22: tvx.ClickerBackend.GetConsumedProductList:output_type -> tvx.GetConsumedProductListResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_tvx_proto_init() }
func file_api_tvx_proto_init() {
	if File_api_tvx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_tvx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableProductListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableProductListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumedProductListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tvx_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumedProductListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_tvx_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tvx_proto_goTypes,
		DependencyIndexes: file_api_tvx_proto_depIdxs,
		EnumInfos:         file_api_tvx_proto_enumTypes,
		MessageInfos:      file_api_tvx_proto_msgTypes,
	}.Build()
	File_api_tvx_proto = out.File
	file_api_tvx_proto_rawDesc = nil
	file_api_tvx_proto_goTypes = nil
	file_api_tvx_proto_depIdxs = nil
}
